version: '3'

services:
  db:
    container_name: ProjectPlaceDB
    image: postgres:latest
    environment:
      - POSTGRES_DB=projectplace
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - projectplacenetwork

  web:
    container_name: ProjectPlaceApp
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - projectplacenetwork

networks:
  projectplacenetwork:
    external: true

