# Generated by Django 4.2.7 on 2023-11-15 17:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Project ID')),
                ('name', models.CharField(max_length=500, verbose_name='Project Name')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=500), django.core.validators.MaxValueValidator(limit_value=999999)], verbose_name='Project Price')),
                ('description', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Project Description')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images', verbose_name='Project Images')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Project.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='project_docs', verbose_name='Project Documents')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Project.project')),
            ],
        ),
    ]
