# Generated by Django 4.2.7 on 2023-11-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(max_length=100, verbose_name='Technology')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='application_type',
            field=models.ManyToManyField(limit_choices_to=3, to='Project.applicationtype', verbose_name='Type of Application Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.ManyToManyField(limit_choices_to=10, to='Project.techstack', verbose_name='Tech Stack'),
        ),
    ]
