# Generated by Django 4.2.7 on 2023-11-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_applicationtype_techstack_project_application_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='application_type',
            field=models.ManyToManyField(to='Project.applicationtype', verbose_name='Type of Application Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.ManyToManyField(to='Project.techstack', verbose_name='Tech Stack'),
        ),
    ]
